# -*- coding: utf-8 -*-
"""Women of Olympic Games.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/gist/riveramatthew/eb7294a4cd65d8db7d23de20f031fbfd/women-of-olympic-games.ipynb
"""

# install RISE for Jupyter presentation
conda install -c conda-forge rise

"""# Women of Olympic Games

#### Brian Rodriguez, John Huynh, Khazrah Nazir, Matthew Rivera, Teresa Gao, YaTing Zhang

# BACKGROUND/MOTIVATION
This idea was sparked by the recent 2022 winter Olympics that happened in Beijing, where women dominated Team USA's medal count, and we wanted to dive deeper into the progression of gender equality in the athletic world and explore both gender's difference in contribution to the Olympics, and their Instagram popularity. To better understand the relationship between the different variables, we have used a variety of visulizations, including histograms, scatter plots, interactive bar charts, and heatmaps.

* Olympic history of female athletes
* Visualizations
    * Histogram
    * Scatter Plot
    * Interactive Heatmap
    * Interactive Vertical Bar Chart

# DATASET INFORMATION
## Data Source: Kaggle

### Datasets:

1. 120 Years of Olympic History
2. Instagram_file

### Python Libraries Used:

* Pandas
* Numpy
* Matplotlib
* Seaborn
* Plotly

## Loading Libraries and the Dataset
"""

# Commented out IPython magic to ensure Python compatibility.
# import necessary libraries
import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv
import seaborn as sns
import matplotlib.pyplot as plt
import re
import plotly.express as px
import cufflinks as cf

# import necessary plotly libraries
from plotly import tools
import plotly.offline as pyo
import plotly.graph_objs as go

pyo.init_notebook_mode()
import plotly.figure_factory as ff
from plotly.offline import download_plotlyjs, init_notebook_mode, plot, iplot

init_notebook_mode(connected=True)

import plotly.graph_objs as go
from google.colab import drive

# %pylab inline
drive.mount('/content/drive')

import os
#print(os.listdir("../input"))

# loading the data
olympics = pd.read_csv('/content/drive/MyDrive/athlete_events.csv')
olympics.head()

"""## Data Exploration"""

# checking for missing values
# the 231,333 in the "Medal" column are rows where the athlete didn't win a medal
print(olympics.isnull().sum())

# sanity check
print(olympics.isnull().sum())

# checking if all NOCs are linked to a unique team
# FRA looks odd
print(olympics.loc[:, ['NOC', 'Team']].drop_duplicates()['NOC'].value_counts().head())

# load the NOC data
noc_country = pd.read_csv('/content/drive/MyDrive/noc_regions.csv')

noc_country.head()

# merge the datasets
olympics_merge = olympics.merge(noc_country,
                                how = 'left')
olympics_merge

# check if there are any NOC codes that doesn't have a match
olympics_merge.loc[olympics_merge['region'].isnull(),['NOC', 'Team']].drop_duplicates()

# replace missing teams with the NOC manually

olympics_merge['region'] = np.where(olympics_merge['NOC']=='SGP', 'Singapore', olympics_merge['region'])
olympics_merge['region'] = np.where(olympics_merge['NOC']=='ROT', 'Refugee Olympic Athletes', olympics_merge['region'])
olympics_merge['region'] = np.where(olympics_merge['NOC']=='UNK', 'Unknown', olympics_merge['region'])
olympics_merge['region'] = np.where(olympics_merge['NOC']=='TUV', 'Tuvalu', olympics_merge['region'])

# some regions are not filled, for simplicity I am filling them with 'Team' value
olympics_merge['region_filled'] = olympics_merge['region'].fillna(olympics['Team'])

# let's add a region to the name
olympics_merge['Name_Region'] = olympics_merge['Name'] + ' (' + olympics_merge['region_filled'] + ')'

# let's split the set for summer and winter games
olympics_summer = olympics_merge[olympics_merge['Season']=='Summer'].copy()
olympics_winter = olympics_merge[olympics_merge['Season']=='Winter'].copy()

# let's split by men and women
olympics_female = olympics_merge[olympics_merge['Sex']=='F'].copy()
olympics_male = olympics_merge[olympics_merge['Sex']=='M'].copy()

# replacing missing values in the "Medal" column
olympics_female['Medal'].fillna(value= 'No Medal', inplace=True)
olympics_male['Medal'].fillna(value= 'No Medal', inplace=True)

olympics_merge.head()

"""# Plotly and the Plotly Figure

## What is Plotly?

*   A JavaScript graphing library
*   Plotly has a Python wrapper

## Why Plotly?
Plotly has a number of unique advantages:

*   Fast and easy to implement simple plots
*   Low code/low effort options using plotly.express
*   (If desired) Extremely customizable
*   Interactive plots by default

## Creating Plotly Figures
Plotly graphs can be created:
1. With **plotly.express** for simple, quick plots ( px )
2. With **plotly.graph_objects** ( go ) for more customization
3. With **plotly.figure_factory** for specific, advanced figures

## The Plotly Figure
A Plotly Figure has 3 main components:
*   **layout** : Dictionary controlling style of the figure
  *   One **layout** per figure
*   **data** : List of dictionaries se ing graph type and data itself
  *   Data + type = a **trace**. There are over 40 types!
  *   Can have multiple traces per graph
*   **frames** : For animated plots (beyond this course)

## Inside a Plotly Figure
"""

figure_config = dict({ "data": [{"type": "bar",
    "x": ["Monday", "Tuesday", "Wednesday",
    "Thursday", "Friday", "Saturday", "Sunday"],
    "y": [28, 27, 25, 31, 32, 35, 36]}],
    "layout": {"title": {"text": "Temperatures of the week",
    "x": 0.5, "font": {'color': 'red', 'size': 15}}}})

fig = go.Figure(figure_config)
fig.show(renderer='colab')

"""# Plotly's instant interactivity
**Plotly provides instant interactivity:**
* Hover over data points
* Extra interactive buttons
![image.png](attachment:image.png)

# Our approach
**Plotly shortcut methods:**
1. **plotly.express**
    * Specify a DataFrame and its columns as arguments
    * Quick, nice but less customization
2. **graph_objects go.X** methods ( **go.Bar()** , **go.Scatter()** ) etc.
    * Many more customization options, but more code needed

# Comparison of Female & Male Athletes in Events
"""

# show the progression of the proportions of female athletes in events
summer_games = olympics_summer.groupby(['Year', 'City', 'Sex'])['Event', 'Name']\
                        .agg({'Event': 'nunique', 'Name': 'nunique'})\
                        .reset_index()\
                        .pivot_table(index=['Year', 'City'], columns='Sex', values=['Event', 'Name'])\
                        .fillna(0)\
                        .reset_index()
summer_games.columns = ['Year', 'City', 'Count of Events - Female', 'Count of Events - Male', 'Female Athletes', 'Male Athletes']

summer_games.iloc[:, 2:] = summer_games.iloc[:, 2:].astype(int)

# I will need common scaling for the comparison of count of events
pcount_full = summer_games['Female Athletes'].tolist() + summer_games['Male Athletes'].tolist()

# scaling for bubble chart
scaled_pcount_f = (summer_games['Female Athletes'] - min(pcount_full)) / (max(pcount_full) - min(pcount_full)) + 0.1
scaled_pcount_m = (summer_games['Male Athletes'] - min(pcount_full)) / (max(pcount_full) - min(pcount_full)) + 0.1

# I need to create the text for the labels. There must be better way to do it, I am looking for clues :-) 
text_f = []
for i in range(summer_games.shape[0]):
    text = 'In ' + \
           str(summer_games.iloc[i,0]) + \
           ', in ' + \
           str(summer_games.iloc[i, 1]) + \
           ', <br>' + \
           str(summer_games.iloc[i,4]) + \
           ' Female Athletes <br>' + \
           'competed in ' + \
           str(summer_games.iloc[i,2]) + \
           ' events.'
    text_f.append(text)

text_m = []
for i in range(summer_games.shape[0]):
    text = 'In ' + \
           str(summer_games.iloc[i,0]) + \
           ', in ' + \
           str(summer_games.iloc[i, 1]) + \
           ', <br>' + \
           str(summer_games.iloc[i,5]) + \
           ' Male Athletes <br>' + \
           'competed in ' + \
           str(summer_games.iloc[i,3]) + \
           ' events.'
    text_m.append(text)

# laying out the bubble chart
trace0 = go.Scatter(
    x=summer_games['Year'],
    y=summer_games['Count of Events - Female'],
    mode='markers',
    marker=dict(
        size=scaled_pcount_f*50,
        symbol='circle-open',
        line=dict(
            width=4
        ),
        color='#2c73d2'
    ),
    name='Female Athletes',
    text=text_f,
    hoverinfo='text'
)
trace1 = go.Scatter(
    x=summer_games['Year'],
    y=summer_games['Count of Events - Male'],
    mode='markers',
    marker=dict(
        size=scaled_pcount_m*50,
        symbol='circle-open',
        line=dict(
            width=4
        ),
        color='#f9f871'),
    name='Male Athletes',
    text=text_m,
    hoverinfo='text'
)

layout1 = go.Layout(
    title='Chasing Equality - Summer Olympics',
    titlefont=dict(
        size=36,
        color='#4b8480'
    ),
    xaxis=dict(
        title='Year',
        color='#4b8480',
        titlefont=dict(
            size=20
        ),
        showline=True,
        linewidth=1,
        linecolor='#4b8480',
        showgrid=False
    ),
    yaxis=dict(
        title='Number of Events',
        color='#4b8480',
        titlefont=dict(
            size=20
        ),
        showline=True,
        linewidth=1,
        linecolor='#4b8480',
        showgrid=False,
        zeroline=False,
    ),
    legend=dict(orientation='h')
)
data1 = [trace0, trace1]

fig1 = go.Figure(data=data1, layout=layout1)

#pyo.iplot(fig1)
fig1.show(renderer='colab')

winter_games = olympics_winter.groupby(['Year', 'City', 'Sex'])['Event', 'Name']\
                        .agg({'Event': 'nunique', 'Name': 'nunique'})\
                        .reset_index()\
                        .pivot_table(index=['Year', 'City'], columns='Sex', values=['Event', 'Name'])\
                        .fillna(0)\
                        .reset_index()
winter_games.columns = ['Year', 'City', 'Count of Events - Female', 'Count of Events - Male', 'Female Athletes', 'Male Athletes']

winter_games.iloc[:, 2:] = winter_games.iloc[:, 2:].astype(int)

# I will need common scaling for the comparison of count of events
pcount_full = winter_games['Female Athletes'].tolist() + winter_games['Male Athletes'].tolist()

# scaling for bubble chart
scaled_pcount_f = (winter_games['Female Athletes'] - min(pcount_full)) / (max(pcount_full) - min(pcount_full)) + 0.1
scaled_pcount_m = (winter_games['Male Athletes'] - min(pcount_full)) / (max(pcount_full) - min(pcount_full)) + 0.1

# I need to create the text for the labels. There must be better way to do it, I am looking for clues :-) 
text_f = []
for i in range(winter_games.shape[0]):
    text = 'In ' + \
           str(winter_games.iloc[i,0]) + \
           ', in ' + \
           str(winter_games.iloc[i, 1]) + \
           ', <br>' + \
           str(winter_games.iloc[i,4]) + \
           ' Female Athletes <br>' + \
           'competed in ' + \
           str(winter_games.iloc[i,2]) + \
           ' events.'
    text_f.append(text)

text_m = []
for i in range(winter_games.shape[0]):
    text = 'In ' + \
           str(winter_games.iloc[i,0]) + \
           ', in ' + \
           str(winter_games.iloc[i, 1]) + \
           ', <br>' + \
           str(winter_games.iloc[i,5]) + \
           ' Male Athletes <br>' + \
           'competed in ' + \
           str(winter_games.iloc[i,3]) + \
           ' events.'
    text_m.append(text)

# laying out the bubble chart
trace0 = go.Scatter(
    x=winter_games['Year'],
    y=winter_games['Count of Events - Female'],
    mode='markers',
    marker=dict(
        size=scaled_pcount_f*50,
        symbol='circle-open',
        line=dict(
            width=4
        ),
        color='#2c73d2'
    ),
    name='Female Athletes',
    text=text_f,
    hoverinfo='text'
)
trace1 = go.Scatter(
    x=winter_games['Year'],
    y=winter_games['Count of Events - Male'],
    mode='markers',
    marker=dict(
        size=scaled_pcount_m*50,
        symbol='circle-open',
        line=dict(
            width=4
        ),
        color='#ABD9FF'),
    name='Male Athletes',
    text=text_m,
    hoverinfo='text'
)

layout1 = go.Layout(
    title='Chasing Equality - Winter Olympics',
    titlefont=dict(
        size=36,
        color='#A6ABBD'
    ),
    xaxis=dict(
        title='Year',
        color='#A6ABBD',
        titlefont=dict(
            size=20
        ),
        showline=True,
        linewidth=1,
        linecolor='#A6ABBD',
        showgrid=False
    ),
    yaxis=dict(
        title='Number of Events',
        color='#A6ABBD',
        titlefont=dict(
            size=20
        ),
        showline=True,
        linewidth=1,
        linecolor='#A6ABBD',
        showgrid=False,
        zeroline=False,
    ),
    legend=dict(orientation='h')
)
data1 = [trace0, trace1]

fig2 = go.Figure(data=data1, layout=layout1)

#pyo.iplot(fig2)
fig1.show(renderer='colab')

"""## Comparison of Total Number of Medals Won Between the 2 Genders: Separated by Seasons"""

summer_athl = olympics_summer.groupby(['region_filled', 'Sex'])['Name']\
                      .count()\
                      .reset_index()\
                      .pivot_table(index='region_filled',
                                   columns='Sex',
                                   values='Name',
                                   fill_value=0)\
                      .reset_index()
summer_athl['Total Athletes'] = summer_athl['F'] + summer_athl['M']
col_rename = {'F': 'Female Athletes', 'M': 'Male Athletes'}
summer_athl = summer_athl.rename(columns=col_rename)

# step 3
summer_med = olympics_summer.dropna(subset=['Medal'])
summer_med_pv = summer_med.groupby(['region_filled','Sex'])['Medal']\
                          .count()\
                          .reset_index()\
                          .pivot_table(index='region_filled',
                                       columns='Sex',
                                       values='Medal',
                                       fill_value=0)\
                          .reset_index()
summer_med_pv['Total'] = summer_med_pv['F'] + summer_med_pv['M']

# step 4
summer_stats = summer_athl.merge(summer_med_pv, how='left')\
                          .fillna(0)
summer_stats_col_rename = {'F': 'Female Medals',
                           'M': 'Male Medals',
                           'Total': 'Total Medals'}
summer_stats = summer_stats.rename(columns=summer_stats_col_rename)
summer_stats['MpFA'] = summer_stats['Female Medals'] / summer_stats['Female Athletes']
summer_stats['MpMA'] = summer_stats['Male Medals'] / summer_stats['Male Athletes']
summer_stats['MpA'] = summer_stats['Total Medals'] / summer_stats['Total Athletes']

# step 5
top_20_med_summer = summer_stats\
                    .sort_values(by='Total Medals', ascending=False)\
                    .iloc[:20, :]\
                    .sort_values(by='MpA')

###--plot--###
trace3 = go.Bar(x=top_20_med_summer['MpFA'],
                y=top_20_med_summer['region_filled'],
                name='Women',
                marker=dict(color='#2c73d2'),
                orientation='h')

trace4 = go.Bar(x=top_20_med_summer['MpMA'],
                y=top_20_med_summer['region_filled'],
                name='Men',
                marker=dict(color='#f9f871'),
                orientation='h')

layout3 = go.Layout(
    title='Medals per Athlete - Summer Games<br>Top 20 Countries',
    font=dict(
        color='#4b8480'
    ),
    titlefont=dict(
        size=28
    ),
    height=800,
    xaxis=dict(
        title='Medals per Athlete', 
        color='#4b8480',
        titlefont=dict(
            size=16
        ), 
        showline=True,
        showgrid=False,
        zeroline=False
    ),
    yaxis=dict(color='#4b8480',showgrid=False, showline=False, automargin=True, ticksuffix='  ')
)
data3 = [trace4,trace3]
fig3 = go.Figure(data=data3, layout=layout3)

#pyo.iplot(fig3)
fig3.show(renderer='colab')

winter_athl = olympics_winter.groupby(['region_filled', 'Sex'])['Name']\
                      .count()\
                      .reset_index()\
                      .pivot_table(index='region_filled',
                                   columns='Sex',
                                   values='Name',
                                   fill_value=0)\
                      .reset_index()
winter_athl['Total Athletes'] = winter_athl['F'] + winter_athl['M']
col_rename = {'F': 'Female Athletes', 'M': 'Male Athletes'}
winter_athl = winter_athl.rename(columns=col_rename)

# step 3
winter_med = olympics_winter.dropna(subset=['Medal'])
winter_med_pv = winter_med.groupby(['region_filled','Sex'])['Medal']\
                          .count()\
                          .reset_index()\
                          .pivot_table(index='region_filled',
                                       columns='Sex',
                                       values='Medal',
                                       fill_value=0)\
                          .reset_index()
winter_med_pv['Total'] = winter_med_pv['F'] + winter_med_pv['M']

# step 4
winter_stats = winter_athl.merge(winter_med_pv, how='left')\
                          .fillna(0)
winter_stats_col_rename = {'F': 'Female Medals',
                           'M': 'Male Medals',
                           'Total': 'Total Medals'}
winter_stats = winter_stats.rename(columns=winter_stats_col_rename)
winter_stats['MpFA'] = winter_stats['Female Medals'] / winter_stats['Female Athletes']
winter_stats['MpMA'] = winter_stats['Male Medals'] / winter_stats['Male Athletes']
winter_stats['MpA'] = winter_stats['Total Medals'] / winter_stats['Total Athletes']

# step 5
top_20_med_winter = winter_stats\
                    .sort_values(by='Total Medals', ascending=False)\
                    .iloc[:20, :]\
                    .sort_values(by='MpA')

###--plot--###
trace5 = go.Bar(x=top_20_med_winter['MpFA'],
                y=top_20_med_winter['region_filled'],
                name='Women',
                marker=dict(color='#2c73d2'),
                orientation='h')

trace6 = go.Bar(x=top_20_med_winter['MpMA'],
                y=top_20_med_winter['region_filled'],
                name='Men',
                marker=dict(color='#ABD9FF'),
                orientation='h')

layout4 = go.Layout(
    title='Medals per Athlete - Winter Games<br>Top 20 Countries',
    font=dict(
        color='#A6ABBD'
    ),
    titlefont=dict(
        size=28
    ),
    height=800,
    xaxis=dict(
        title='Medals per Athlete', 
        color='#A6ABBD',
        titlefont=dict(
            size=16
        ), 
        showline=True,
        showgrid=False,
        zeroline=False
    ),
    yaxis=dict(
        color='#A6ABBD',
        showgrid=False,
        showline=False,
        automargin=True,
        ticksuffix='  ')
)
data4 = [trace6,trace5]
fig4 = go.Figure(data=data4, layout=layout4)

#pyo.iplot(fig4)
fig4.show(renderer='colab')

"""## Breakdown of Medals won by Women"""

# how many medals of each color each female athlete earned
# we can also check, how many events they participated in with no medal at all
fmedals = olympics_female.groupby(['Name_Region', 'Medal'])['Event']\
             .count()\
             .reset_index()\
             .pivot_table(index='Name_Region',
                          columns='Medal',
                          values='Event',
                          fill_value=0)\
             .reset_index()

# let's reorder columns and add Total as the sum of Bronze, Silver, Gold
fmedals['Total'] = fmedals['Bronze'] + fmedals['Silver'] + fmedals['Gold']
fmedals = fmedals[['Name_Region', 'No Medal', 'Bronze', 'Silver', 'Gold', 'Total']]

# take only ones with 10 or more medals
f10meds = fmedals[fmedals['Total'] >= 10].sort_values(by='Total').copy()

# now onto the plot
data_m = []

for i in range(f10meds.shape[0]):
    trace = go.Scatter(
        x=list(range(1, f10meds.iloc[i,5]+1)),
        y=[f10meds.iloc[i,0]] * f10meds.iloc[i,5],
        mode='markers',
        marker=dict(
            size=30,
            color=['#A48E65'] * f10meds.iloc[i,2]+\
                  ['#DFE0DF'] * f10meds.iloc[i,3]+\
                  ['#D5A419'] * f10meds.iloc[i,4],
            line=dict(color='white',
                      width=1)
        ),
        showlegend=False,
        text=str(f10meds.iloc[i,0]) +\
        '<br>won ' +\
        str(f10meds.iloc[i, 5]) +\
        ' medals in total.',
        hoverinfo='text'
    )
    data_m.append(trace)

layout_m = go.Layout(
    title='Top Olympic Medalists - Women',
    titlefont=dict(
        size=24,
        color='#4b8480'
    ),
    height=800, 
    hovermode='closest', 
    yaxis=dict(
        color='#4b8480',
        automargin=True,
    ), 
    xaxis=dict(
        color='#4b8480',
        showgrid=False,
        zeroline=False))
fig_m = go.Figure(data=data_m, layout=layout_m)

#pyo.iplot(fig_m)
fig_m.show(renderer='colab')

# let's take the subset of top medalists to contain data necessary for plotting
f10meds_full = olympics_female[olympics_female['Name_Region'].isin(f10meds['Name_Region'])]
f10meds_full = f10meds_full[['Name_Region',
                             'Season',
                             'Age',
                             'Year',
                             'City',
                             'Event',
                             'Medal']]

# for better display, let's do this:
def insert_break(s):
    '''
    This function inserts break point in the
    middle of the Event's name.
    arg: string
    returns: string with breakpoint inserted
    '''
    split_s = s.split(' ')
    split_s.insert(int(len(split_s)/2), '<br>')
    s = ' '.join(split_s)
    return s

# then, let's map the medals to colors
medals_map = {'No Medal': '#2c73d2',
              'Bronze': '#A48E65',
              'Silver': '#DFE0DF',
              'Gold' : '#D5A419'}

f10meds_full['Event_br'] = f10meds_full['Event'].apply(insert_break)
f10meds_full['Medal_clr'] = f10meds_full['Medal'].map(medals_map)

# for hover text
text_all = []
for i in range(f10meds_full.shape[0]):
    text = 'In ' +\
        f10meds_full.iloc[i, 1] +\
        ' Games in ' +\
        f10meds_full.iloc[i, 4] +\
        ' (' +\
        str(f10meds_full.iloc[i, 3]) +\
        '),<br>' +\
        f10meds_full.iloc[i, 0] +\
        '<br>won ' +\
        f10meds_full.iloc[i, 6] +\
        ' in<br>' +\
        f10meds_full.iloc[i, 7] +\
        '<br>She was ' +\
        str(f10meds_full.iloc[i, 2]) +\
        ' at the time.'
    text_all.append(text)
f10meds_full['Text'] = text_all

# the main loop iterates over the dataframe with top medalists and creates figure elements
data_m = []
buttons_m = []

for i in range(f10meds.shape[0]):
    subset = f10meds_full[f10meds_full['Name_Region'] == str(f10meds.iloc[i,0])]
    x_ax_ticks = pd.unique(subset['Year'])
    # I need to do below, because I need to display something first, without user interaction
    # looking for help here ;-)
    
    if i == f10meds.shape[0] - 1:
        trace_m = go.Scatter(
            x=subset['Year'],
            y=subset['Event_br'],
            mode='markers',
            marker=dict(size=30, color=subset['Medal_clr']),
            text=subset['Text'],
            hoverinfo='text',
            visible=True
            )
    else:
        trace_m = go.Scatter(
            x=subset['Year'],
            y=subset['Event_br'],
            mode='markers',
            marker=dict(size=30, color=subset['Medal_clr']),
            text=subset['Text'],
            hoverinfo='text',
            visible=False
            )
        
    data_m.append(trace_m)
    
    visible_traces = np.full(f10meds.shape[0], False)
    visible_traces[i] = True
    
    button_m = dict(
        label=str(f10meds.iloc[i,0]),
        method= 'update',
        args=[
            dict(
                visible=visible_traces
            ),
            dict(
                xaxis=dict(
                    tickvals=x_ax_ticks,
                    showgrid=False,
                    tickfont=dict(
                        size=14
                    )
                )
            )
        ]
    )
    buttons_m.append(button_m)
    
    updatemenus = [
        dict(
            buttons=buttons_m,
            active=f10meds.shape[0] - 1,
            showactive=True,
            x=0.5,
            xanchor='center',
            y=1.1,
            yanchor='top'
            )
        ]

layout_m = go.Layout(
    title='Top medalists - breakdown',
    height=600,
    font=dict(
        color='#4b8480'
        ),
    titlefont=dict(
        size=24
        ),
    xaxis=dict(
        tickvals=x_ax_ticks,
        showgrid=False,
        tickfont=dict(size=14)
        ),
    yaxis=dict(
        automargin=True
        ),
    hovermode='closest',
    updatemenus=updatemenus
)
fig = go.Figure(data=data_m, layout=layout_m)

#pyo.iplot(fig)    
fig.show(renderer='colab')

# WomenInOlympics = olympics_merge[(olympics_merge['Sex'] == 'F') & (olympics_merge.Season == 'Summer')]
SummerOlympics = olympics_merge[olympics_merge['Season'] == 'Summer']

SummerOlympics.head()

sns.set(style="whitegrid")
plt.figure(figsize=(20, 10))
sns.countplot(x='Year', hue = 'Sex', data=SummerOlympics)
plt.title('Women medals per edition of the Games')

# WomenInOlympics = olympics_merge[(olympics_merge['Sex'] == 'F') & (olympics_merge.Season == 'Winter')]
WinterOlympics = olympics_merge[olympics_merge['Season'] == 'Winter']

WinterOlympics.head()

sns.set(style="whitegrid")
plt.figure(figsize=(20, 10))
sns.countplot(x='Year', hue = 'Sex', data=WinterOlympics)
plt.title('Women medals per edition of the Games')

"""## What Sports are Men/Women Especially Good at?"""

#Q2: are there sports that man/woman are especially good at?
# counting the number of events, in which female and male athletes competed, by year and sport
summer_sports = olympics_summer.groupby(['Year', 'Sport', 'Sex'])['Event']\
                         .agg('nunique')\
                         .reset_index()\
                         .pivot_table(index=['Year','Sport'], columns='Sex', values='Event', fill_value=0)\
                         .reset_index()

# assigning a score
summer_sports['Score'] = (summer_sports['F'] - summer_sports['M']) / (summer_sports['F'] + summer_sports['M'])

# final pivot for heatplot
summer_sports_pivot = summer_sports.pivot_table(index='Sport', columns='Year', values='Score').reset_index()

# plot set up
trace2 = go.Heatmap(z=np.array(summer_sports_pivot.iloc[:,1:]),
                    x=summer_sports_pivot.columns.tolist()[1:],
                    y=summer_sports_pivot['Sport'],
                    colorscale=[[0, '#f9f871'], [0.5, '#00d9b3'], [1, '#2c73d2']],
                    xgap=0.9,
                    ygap=0.9,
                    colorbar=dict(
                        title='Equality score',
                        titleside='right',
                        titlefont=dict(
                            size=20,
                            color='#4b8480'),
                        outlinecolor='white',
                        tickcolor='#4b8480',
                        tickfont=dict(color='#4b8480'),
                        tickmode='array',
                        tickvals=[-0.95, 0, 0.95],
                        ticktext=['Only<br>Men', 'Perfectly<br>Equal', 'Only<br>Women']
                    )
                   )

data2 = [trace2]
layout2 = go.Layout(
    title='In summer, men lift weights, women swim(synchronously)',
    titlefont=dict(
        size=24,
        color='#4b8480'
    ),
    height=800,
    #margin=dict(l=180,t=100),
    xaxis=dict(title='Year', 
               titlefont=dict(
                   size=16
               ),
               showgrid=False, 
               color='#4b8480'
              ),
    yaxis=dict(
               color='#4b8480',
               tickfont=dict(
                   size=9
               ),
               automargin=True,
               showgrid=False
              ))
fig2 = go.Figure(data=data2, layout=layout2)

#pyo.iplot(fig2)
fig2.show(renderer='colab')

# counting the number of events, in which female and male athletes competed, by year and sport
winter_sports = olympics_winter.groupby(['Year', 'Sport', 'Sex'])['Event']\
                         .agg('nunique')\
                         .reset_index()\
                         .pivot_table(index=['Year','Sport'], columns='Sex', values='Event', fill_value=0)\
                         .reset_index()

# assigning a score
winter_sports['Score'] = (winter_sports['F'] - winter_sports['M']) / (winter_sports['F'] + winter_sports['M'])

# final pivot for heatplot
winter_sports_pivot = winter_sports.pivot_table(index='Sport', columns='Year', values='Score').reset_index()

# plot set up
trace2 = go.Heatmap(z=np.array(winter_sports_pivot.iloc[:,1:]),
                    x=winter_sports_pivot.columns.tolist()[1:],
                    y=winter_sports_pivot['Sport'],
                    colorscale=[[0, '#ABD9FF'], [0.5, '#76a5e9'], [1, '#2c73d2']],
                    xgap=0.9,
                    ygap=0.9,
                    colorbar=dict(
                        title='Equality score',
                        titleside='right',
                        titlefont=dict(
                            size=20,
                            color='#A6ABBD'),
                        outlinecolor='white',
                        tickcolor='#A6ABBD',
                        tickfont=dict(
                            color='#A6ABBD'
                        ),
                        tickmode='array',
                        tickvals=[-0.95, 0, 0.95],
                        ticktext=['Only<br>Men', 'Perfectly<br>Equal', 'Only<br>Women']
                    ),
                    zmin=-1,
                    zmax=1
                   )

data2 = [trace2]
layout2 = go.Layout(
    title='But in winter, everyone skates or skiis',
    titlefont=dict(
        size=24,
        color='#A6ABBD'
    ),
    height=800,
    #margin=dict(l=180,t=100),
    xaxis=dict(title='Year', 
               titlefont=dict(
                   size=16
               ),
               showgrid=False, 
               color='#A6ABBD'
              ),
    yaxis=dict(
               color='#A6ABBD',
               tickfont=dict(
                   size=12
               ),
               automargin=True,
               showgrid=False
              )
)
fig2 = go.Figure(data=data2, layout=layout2)

#pyo.iplot(fig2)
fig2.show(renderer='colab')

"""## Popularity Of Medalist Through Instagram"""

olympic_sheet = pd.read_excel("/content/drive/MyDrive/Instagram_file.xlsx")
Beijing = pd.read_excel("/content/drive/MyDrive/Instagram_file.xlsx", sheet_name="Beijing2022")
Tokyo = pd.read_excel("/content/drive/MyDrive/Instagram_file.xlsx", sheet_name="Tokyo2020")
olympic_sheet.drop(["Gold", "Silver","Bronze"],axis=1, inplace=True) #this line can only be run once
olympic_sheet.rename(columns={"Athlete": "Athlete Name", "Total": "Total Medals", "Instagram": "Instagram Followers (Millions)"}, inplace=True)
Beijing.rename(columns={"Athlete": "Athlete Name", "Total": "Total Medals", "Instagram": "Instagram Followers (Millions)"}, inplace=True)
Tokyo.rename(columns={"Athlete": "Athlete Name", "Total": "Total Medals", "Instagram": "Instagram Followers (Millions)"}, inplace=True)

fig = px.scatter(olympic_sheet, x="Total Medals", y="Instagram Followers (Millions)",
           hover_data=['Athlete Name', 'Nation', 'Sport', 'Years', 'Games', 'Gender',
       'Total Medals', 'Instagram Followers (Millions)'],
           color="Gender",
           title="Instagram Followers Per Total Medals From Past 20 Years",
                 )
           
fig.update_traces(marker=dict(size=12,
                              line=dict(width=2,
                                        color='DarkSlateGrey')),
                  selector=dict(mode='markers')).show(renderer='colab')

male = Beijing[Beijing.Gender=="M"]["Total_Medals"].mean()
female = Beijing[Beijing.Gender=="F"]["Total_Medals"].mean()
fig = px.bar(Beijing , x=["Male","Female"], y=[male, female], 
             title = " Average Medals In Beijing 2022",
             color=["Male","Female"],
             labels={"y":"Average Total Medals", "x":"Gender"},
            width=300)
fig.show(renderer="colab")
#pyo.iplot(fig)

male = int(Beijing[Beijing.Gender=="M"]["Instagram Followers (Millions)"].mean())
female = int(Beijing[Beijing.Gender=="F"]["Instagram Followers (Millions)"].mean())
fig = px.bar(Beijing , x=["Male","Female"], y=[male, female], 
             title = "Average Instagram Beijing 2022",
             color=["Male","Female"],
             labels={"y":"Average Instagram Folowers", "x":"Gender"},
            width=300)
fig.show(renderer="colab")
#pyo.iplot(fig)

male = Tokyo[Tokyo.Gender=="M"]["Total_Medals"].mean()
female = Tokyo[Tokyo.Gender=="F"]["Total_Medals"].mean()
fig_2 = px.bar(Tokyo , x=["Male","Female"], y=[male, female], 
             title = " Average Medals Tokyo 2020",
             color=["Male","Female"],
             labels={"y":"Average Total Medals", "x":"Gender"},
            width=300)
fig_2.show(renderer="colab")
#pyo.iplot(fig_2)

male = int(Tokyo[Tokyo.Gender=="M"]["Instagram Followers (Millions)"].mean())
female = int(Tokyo[Tokyo.Gender=="F"]["Instagram Followers (Millions)"].mean())
fig = px.bar(Tokyo , x=["Male","Female"], y=[male, female], 
             title = "Average Instagram Tokyo 2020",
             color=["Male","Female"],
             labels={"y":"Average Instagram Folowers", "x":"Gender"},
            width=300)
fig.show(renderer="colab")
#pyo.iplot(fig)

"""# THANK YOU!!"""